### ISSUE TITLE
Wondering why using get_geoserver_cascading_workspace

### ISSUE THREAD

**Issue by pchevali** [GeoNode/geonode-importer#222]
Hi,

In the importer plugin there are lots of references to "get_geoserver_cascading_workspace", however this geoserver workspace seems to be dedicated to remote services as far I understand.

Is there a reason to return the value of CASCADE_WORKSPACE instead of DEFAULT_WORKSPACE here ?

Thanks

**Comment by mattiagiupponi** [comment]
Hi, it was used mainly because 99% of the time is the same workspace and for the "create=True" option. But yes, i guess is worth to change it and use the `DEFAULT WORKSPACE`

**Comment by mattiagiupponi** [comment]
Code updated, will be used from the new versions of the importer
