### ISSUE TITLE
Include the id of the new resource inside the executionrequest outputs

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-importer#240]
Currently, only the URL of the new resource is included inside the output parameters of an execution request for an upload.
We want to include the ID of the new new resource.

This requires expanding the output params, since at the moment the detail URLs are returned as an array in case of multiple uploads.

The output paramas will change from:
```json
"output_params": {
	"detail_url": [
		<url1>,
		<url2>
	]
}
```

to:
```json
"output_params": {
	"resources": [
		{
			"id": <pk1>,
			"detail_url": <url1>,
		},
		{
			"id": <pk2>
			"detail_url": <url2>,
		}
	]
}
```

This must be handled by the client. A task for it will be created.

**Comment by mattiagiupponi** [comment]
@giohappy PR ready, we need to wait the fix on the FE before merging

**Comment by giohappy** [comment]
@mattiagiupponi client is ready to support the change (https://github.com/GeoNode/geonode-mapstore-client/pull/1749)
